import { createApp } from 'vue';
import App from './App';
import router from './router';
import store from './store';
import '/@/style/index.scss';
import 'ant-design-vue/dist/antd.css';
import { Button } from 'ant-design-vue';
const app = createApp(App).use(store).use(router);
app.use(Button);
app.mount('#app');
